import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { asrSegments, requireTimestamps } from '../../qwen-media-runtime/src/asr_timeline.mjs';
import { shareUrl, prepare } from '../../yy-douyin-video/scripts/prepare_video.mjs';
import { validateStoryboard, fields } from '../../yy-douyin-video/src/storyboard.mjs';
import { render } from '../../yy-douyin-video/scripts/render_storyboard.mjs';
import { run, writeJson, readJson } from '../../yy-douyin-video/src/common.mjs';

const scriptDir = fileURLToPath(new URL('../../yy-douyin-video/scripts/', import.meta.url));
const root = process.env.QWEN_TEST_OUTPUT_DIR || path.resolve(scriptDir, '../../work/tests');
await fs.mkdir(root, { recursive: true });
const output = await fs.mkdtemp(path.join(root, 'workflow-test-'));
const source = path.join(output, 'synthetic.mp4');
await run('ffmpeg', ['-v', 'error', '-nostdin', '-n', '-f', 'lavfi', '-i', 'color=c=red:s=320x240:r=25:d=2', '-f', 'lavfi', '-i', 'color=c=blue:s=320x240:r=25:d=2', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-filter_complex', '[0:v][1:v]concat=n=2:v=1:a=0[v]', '-map', '[v]', '-map', '2:a', '-c:v', 'libx264', '-c:a', 'aac', '-shortest', source]);
const media = await prepare({ file: source, out: path.join(output, 'task') });
assert.ok(Math.abs(media.durationSeconds - 4) < 0.1);
assert.ok(media.audio);
assert.ok(media.candidateCuts.some((cut) => Math.abs(cut - 2) < 0.1));
assert.equal(shareUrl('分享 [https://v.douyin.com/abc/](https://v.douyin.com/abc/)'), 'https://v.douyin.com/abc/');
assert.throws(() => shareUrl('https://v.douyin.com.evil.test/a'));
assert.throws(() => shareUrl('https://user:pass@v.douyin.com/a'));
const segments = asrSegments({ transcripts: [{ sentences: [{ begin_time: 1500, end_time: 2500, text: '跨镜头台词' }] }] });
assert.equal(segments[0].start, 1.5);
assert.throws(() => asrSegments({ transcripts: [{ sentences: [{ text: '缺失时间' }] }] }));
assert.throws(() => requireTimestamps([], '已有台词'));
const detail = Object.fromEntries(Object.keys(fields).map((key) => [key, '合成测试，无真实语义']));
const data = { summary: '<script>alert(1)</script> 合成验证，不是抖音分析', shots: [{ ...detail, start: 0, end: 2, frames: [0.51] }, { ...detail, start: 2, end: media.durationSeconds, frames: [2.51] }] };
const shots = validateStoryboard(data, media, segments);
assert.equal(shots[0].speech[0].id, shots[1].speech[0].id);
assert.ok(shots[1].speech[0].continues);
const bad = structuredClone(data); bad.shots[1].start = 2.5;
assert.throws(() => validateStoryboard(bad, media, segments));
const outside = structuredClone(data); outside.shots[0].frames = [2];
assert.throws(() => validateStoryboard(outside, media, segments));
const missing = structuredClone(data); missing.shots.pop();
assert.throws(() => validateStoryboard(missing, media, segments));
await writeJson(path.join(output, 'shots.json'), data);
await writeJson(path.join(output, 'asr.json'), { results: [{ text: '跨镜头台词', segments }] });
const report = await render({ media: path.join(output, 'task/media.json'), shots: path.join(output, 'shots.json'), asr: path.join(output, 'asr.json'), out: path.join(output, 'report') });
const html = await fs.readFile(report, 'utf8');
assert.ok(html.includes('&lt;script&gt;'));
assert.ok(!html.includes('<script>alert'));
const saved = await readJson(path.join(output, 'report/storyboard.json'));
assert.equal(saved.speechTimeline.length, 1);
assert.ok(saved.shots[0].images[0].actualTime >= 0.51);
assert.ok(saved.shots[0].images[0].actualTime < 2);
await run(process.execPath, [path.join(scriptDir, 'build_prompt.mjs'), '--media', path.join(output, 'task/media.json'), '--asr', path.join(output, 'asr.json'), '--out', path.join(output, 'prompt.txt')]);
assert.ok((await fs.readFile(path.join(output, 'prompt.txt'), 'utf8')).includes('跨镜头台词'));
console.log(JSON.stringify({ result: 'WORKFLOW_TESTS_OK', report }, null, 2));
